### DISCUSSION TITLE
"flask db migrate" error in a Docker container

### DISCUSSION THREAD

**Discussion by yuanyanhui** [miguelgrinberg/Flask-Migrate#548] [Q&A]
I have a falsk app with a postgresql database (DATABASE_URL=postgresql://dbuser:dbuser@db:5432/appdb).

```
docker-compose.yml
services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 app:app
    volumes:
      - static_volume:/home/app/web/app/static
      - media_volume:/home/app/web/app/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: always

 db:
    image: postgres:15
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always
```

If I run ` sudo docker-compose -f docker-compose.yml exec web flask db migrate` , I get the following error
` File "/usr/local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "db" (172.24.0.2), port 5432 failed: FATAL:  password authentication failed for user "dbuser"`.

I can connect to the db conainter and create tables by `sudo docker-compose -f docker-compose.yml exec web python manage.py create_db`. The app works fine with database queries.

```
manage.py
from flask.cli import FlaskGroup
from app import app, db
from app.models import User


cli = FlaskGroup(app)

@cli.command("create_db")
def create_db():
    db.drop_all()
    db.create_all()
    db.session.commit()
```
